name: Build and Run Go Program

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node: ["10.0.2.154", "10.0.2.155"]

    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ matrix.node }} >> ~/.ssh/known_hosts

      - name: Deploy to ${{ matrix.node }}
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          REDIS_HOST: "your_redis_host_ip"  # Replace with actual Redis IP or pass as a secret
          DB_HOST: "your_db_host_ip"        # Replace with actual DB IP or pass as a secret
        run: |
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@${{ matrix.node }} << EOF
            docker pull sarakalhussain/devops:latest
            docker stop web_app || true
            docker rm web_app || true
            docker run -d \
              -p 5000:5000 \
              --name web_app \
              -e REDIS_HOST="$REDIS_HOST" \
              -e DB_HOST="$DB_HOST" \
              -e DB_USER="user" \
              -e DB_PASSWORD="password" \
              -e DB_NAME="mydatabase" \
              sarakalhussain/devops:latest
          EOF
