name: Build and Run python Program

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        nodes: ["10.0.2.37", "10.0.2.38"]

    steps:
      - name: Deploy to ${{ matrix.nodes }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ matrix.nodes }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa $SSH_USERNAME@${{ matrix.nodes }} "
            docker pull sarakalhussain/devops:latest && \
            docker stop web_app || true && \
            docker rm web_app || true && \
            docker run -d \
              -p 5000:5000 \
              --name web_app \
              -e REDIS_HOST=redis \
              -e DB_HOST=db \
              -e DB_USER=user \
              -e DB_PASSWORD=password \
              -e DB_NAME=mydatabase \
              sarakalhussain/devops:latest
          "

