name: Test
on:
  pull_request:
    branches:
      - main 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
         - name: Repo Checker  
           uses: actions/checkout@v2
         
         - name: Run tests
           run: python test_app.py
      